version: "3"

services:
  httpd:
    image: "httpd:alpine"
    ports:
     - "$HTTPD_PORT:80"
    volumes:
     - "./public:/usr/local/apache2/htdocs"
    working_dir: "/usr/local/apache2/htdocs"

  lighttpd:
    build: "./lighttpd"
    image: "lighttpd"
    ports:
     - "$LIGHTTPD_PORT:80"
    volumes:
     - "./public:/var/www/localhost/htdocs"
    working_dir: "/var/www/localhost/htdocs"

  nginx:
    image: "nginx:alpine"
    ports:
     - "$NGINX_PORT:80"
    volumes:
     - "./public:/usr/share/nginx/html"
    working_dir: "/usr/share/nginx/html"

