version: "3"

services:
  httpd:
    image: "httpd:alpine"
    ports:
     - "$HTTPD_PORT:80"

  lighttpd:
    build: "./lighttpd"
    image: "lighttpd"
    ports:
     - "$LIGHTTPD_PORT:80"

  nginx:
    image: "nginx:alpine"
    ports:
     - "$NGINX_PORT:80"

