version: "3"

services:
  cadvisor:
    image: "google/cadvisor"
    ports:
     - "$CADVISOR_PORT:8080"
    volumes:
     - "/:/rootfs:ro"
     - "/var/run:/var/run:rw"
     - "/sys:/sys:ro"
     - "/var/lib/docker:/var/lib/docker:ro"
     - "/dev/disk:/dev/disk:ro"

  httpd:
    depends_on:
     - "cadvisor"
    image: "httpd:alpine"
    ports:
     - "$HTTPD_PORT:80"
    volumes:
     - "./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
     - "./public:/usr/local/apache2/htdocs"
    working_dir: "/usr/local/apache2/htdocs"

  lighttpd:
    build: "./lighttpd"
    depends_on:
     - "cadvisor"
    image: "lighttpd"
    ports:
     - "$LIGHTTPD_PORT:80"
    volumes:
     - "./lighttpd/lighttpd.conf:/etc/lighttpd/lighttpd.conf"
     - "./public:/var/www/localhost/htdocs"
    working_dir: "/var/www/localhost/htdocs"

  nginx:
    depends_on:
     - "cadvisor"
    image: "nginx:alpine"
    ports:
     - "$NGINX_PORT:80"
    volumes:
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
     - "./public:/usr/share/nginx/html"
    working_dir: "/usr/share/nginx/html"

